### ISSUE TITLE
PyTorch 1.11.0 Built with GPU Support

### ISSUE THREAD

**Issue by grassjelly** [Qengineering/PyTorch-Jetson-Nano#2]
Hi, just wondering if the wheel for Jetson Nano PyTorch 1.11.0 supports GPU? After installing the wheel `torch.cuda.is_available()` returns False.

Thank you! :)

**Comment by Qengineering** [comment]
@grassjelly,

You need to have an **Ubuntu 20.04 OS** on your Jetson Nano, since PyTorch 1.11 requires Python 3.7.
The original JetPack has Python 3.6.

![image](https://user-images.githubusercontent.com/44409029/162582835-0857a874-c106-4bd0-b20a-752cf4925075.png)

**Comment by grassjelly** [comment]
Thanks
