### ISSUE TITLE
Bugs about torchvision installation

### ISSUE THREAD

**Issue by JSHZT** [Qengineering/PyTorch-Jetson-Nano#6]
My JETPACK version is 4.6.2, as the documentation says, the torch version I installed is 1.10.0, and when I try to install the included torchvision wheel, it throws an error
`jshzt@ubuntu:~/hzt/whl$ pip3 install torch-1.10.0a0+git36449ea-cp36-cp36m-linux_aarch64.whl 
Processing ./torch-1.10.0a0+git36449ea-cp36-cp36m-linux_aarch64.whl
Collecting typing-extensions (from torch==1.10.0a0+git36449ea)
  Using cached https://files.pythonhosted.org/packages/45/6b/44f7f8f1e110027cf88956b59f2fad776cca7e1704396d043f89effd3a0e/typing_extensions-4.1.1-py3-none-any.whl
Collecting dataclasses; python_version < "3.7" (from torch==1.10.0a0+git36449ea)
  Using cached https://files.pythonhosted.org/packages/fe/ca/75fac5856ab5cfa51bbbcefa250182e50441074fdc3f803f6e76451fab43/dataclasses-0.8-py3-none-any.whl
Installing collected packages: typing-extensions, dataclasses, torch
Successfully installed dataclasses-0.8 torch-1.10.0a0+git36449ea typing-extensions-4.1.1

jshzt@ubuntu:~/hzt/whl$ pip3 install torchvision-0.11.0a0+fa347eb-cp36-cp36m-linux_aarch64.whl 
Processing ./torchvision-0.11.0a0+fa347eb-cp36-cp36m-linux_aarch64.whl
Collecting numpy (from torchvision==0.11.0a0+fa347eb)
  Using cached https://files.pythonhosted.org/packages/51/60/3f0fe5b7675a461d96b9d6729beecd3532565743278a9c3fe6dd09697fa7/numpy-1.19.5.zip
Collecting torch (from torchvision==0.11.0a0+fa347eb)
  Could not find a version that satisfies the requirement torch (from torchvision==0.11.0a0+fa347eb) (from versions: )
No matching distribution found for torch (from torchvision==0.11.0a0+fa347eb)
`

**Comment by Qengineering** [comment]
I could not reproduce your issue. Used a fresh SD-card with JetPack 4.6.2.
Followed all instructions on the [guide](https://qengineering.eu/install-pytorch-on-jetson-nano.html). No errors at all.
Are you sure you have installed all dependencies? Not using a virtual environment?

![Screenshot from 2023-04-02 18-30-47](https://user-images.githubusercontent.com/44409029/229366559-40d0ad53-9d8d-48d6-8452-2d43c0f442ff.png)

![Screenshot from 2023-04-02 18-35-18](https://user-images.githubusercontent.com/44409029/229366572-815e4220-cd14-470b-8a5b-d9b0d3c6ed3b.png)

**Comment by JSHZT** [comment]
Thank you for your reply，maybe I have not installed all dependencies.I wil follow the guide again!

**Comment by Qengineering** [comment]
Also, try to run Torch in python before install torchvision.  
Torchvision trying to install Torch by itself as a dependency could indicate a not functional installation of Torch in python.
![image](https://user-images.githubusercontent.com/44409029/229546608-35f86272-c8b3-4913-b2a3-b039a88805bf.png)

**Comment by JSHZT** [comment]
Thank you, I have reinstalled all dependencies, and I have successfully installed torchision.
